// loader
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

// labour list
export const LABOUR_LIST_REQUEST = 'LABOUR_LIST_REQUEST';
export const LABOUR_LIST_RESPONSE = 'LABOUR_LIST_RESPONSE';
export const LABOUR_LIST_FAILED = 'LABOUR_LIST_FAILED';

// labour details
export const LABOUR_DETAILS_REQUEST = 'LABOUR_DETAILS_REQUEST';
export const LABOUR_DETAILS_RESPONSE = 'LABOUR_DETAILS_RESPONSE';
export const LABOUR_DETAILS_FAILED = 'LABOUR_DETAILS_FAILED';
